# Configure the Sober launch options.
launch:

  # Flatpak name.
  flatpak-name: "org.vinegarhq.Sober"

  # Place ID. You usually shouldn't change this.
  place-id: 16855862021

  # The domain to go to after launching.
  goto-domain: "test.acwapic.rbx"

# Configure the window options.
window:

  # Window position.
  position-x: 40
  position-y: 40

  # Window size.
  size-x: 800
  size-y: 600

  # The "input field" click position (absolute).
  # Remember that the main content of the page is guranteed to be at least ~200px down from the window position.
  input-x: 50
  input-y: 240

  # ms
  delay-bewtween-inputs: 40


# Configure log detections. You probably shouldn't change this mostly.
detection:

  # The value to check for first in the log output.
  rbx-identifier: "[FLog::Output]"

  # After the above check successfully runs, The slice index to pass to the user functions.
  slice-index: 74

  # The value to check for to actually activate the user functions.
  start-processing-call: "CatWeb v"

  # Ignore values
  ignore-values:
  - "Settings Date "